# aws go image 
# FROM public.ecr.aws/docker/library/golang:alpine3.16
FROM public.ecr.aws/lambda/go:1.2022.11.15.11
LABEL Terry Kim <terry960302@gmail.com>


WORKDIR /app

ADD go.mod /app
ADD go.sum /app

RUN apk update && \
    apk add git && \
    go get -d ./...

COPY . /app

EXPOSE 8000
ENV PROFILE=dev

RUN go build -o main.go
CMD ["./main"]

