database:
  user: postgres
  password: postgres
  net: tcp
  host: localhost
  port: 5432
  dbname: marketbill-test

server:
  port: 8000

api:
  host : https://sens.apigw.ntruss.com
  service_id: ncp:sms:kr:290881020329:marketbill-project
  access_key_id : 2aJkrtHdUtk5NP4oG8yh
  secret_key : x2A3OXOz0P1qmaLDnTiqo2dQ7if6BzOElQEPNg6b
